# Image nodejs: 
FROM node:19-alpine:3.16 

WORKDIR /usr/src/app

RUN apt-get update \ 
&& apt-get -y install vim 

RUN npm install express

RUN npm install http

RUN npm install tail

RUN mkdir -p /usr/src/app

COPY index.js /usr/src/app

RUN nohup node index &
